### PR TITLE
feat: add build files

### PR DESCRIPTION
**Pull request by shayan-ginbits**

### CODE REVIEW

**Comment by ginbits-bots** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ginbits/react-material-ui-carousel/pull/11#" title="Author self-approved">shayan-ginbits</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ginbits%2Freact-material-ui-carousel).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ginbits/react-material-ui-carousel/blob/build/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ginbits-bots** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by: *<a href="https://github.com/ginbits/react-material-ui-carousel/pull/11#" title="Author self-approved">shayan-ginbits</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ginbits%2Freact-material-ui-carousel).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ginbits/react-material-ui-carousel/blob/build/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by gregpavl** [comment]
/label todo 

needs a workflow is we continue pushing to `build` branch

**Pull request merged**
