### PR TITLE
fix: add forwardRef to carousel and make next and prev functions accessible from outside

### PR DESCRIPTION
**Pull request by shayan-ginbits**
- Wrapped the Carousel with `forwardRef `
- Made next and prev functions accessible through ref

### CODE REVIEW

**Comment by ginbits-bots** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ginbits/react-material-ui-carousel/pull/2#" title="Author self-approved">shayan-ginbits</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ginbits%2Freact-material-ui-carousel).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ginbits/react-material-ui-carousel/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ginbits-bots** [comment]
@shayan-ginbits: GitHub didn't allow me to request PR reviews from the following users: daniellalasa2.

Note that only [ginbits members](https://github.com/orgs/ginbits/people) and repo collaborators can review this PR, and authors cannot review their own PRs.

<details>

In response to [this](https://github.com/ginbits/react-material-ui-carousel/pull/2#issuecomment-2255925835):

>/cc @daniellalasa2 


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by gregpavl** [comment]
@shayan-ginbits  
edit the owners in the `release` repo to start assign the correct reviewers

**Review by daniellalasa2 — APPROVED** [review]

**Comment by ginbits-bots** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ginbits/react-material-ui-carousel/pull/2#pullrequestreview-2205186831" title="Approved">daniellalasa2</a>*, *<a href="https://github.com/ginbits/react-material-ui-carousel/pull/2#" title="Author self-approved">shayan-ginbits</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ginbits%2Freact-material-ui-carousel).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ginbits/react-material-ui-carousel/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ginbits-bots** [comment]
@daniellalasa2: changing LGTM is restricted to collaborators

<details>

In response to [this](https://github.com/ginbits/react-material-ui-carousel/pull/2#issuecomment-2256139628):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes-sigs/prow](https://github.com/kubernetes-sigs/prow/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by ginbits-bots** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/ginbits/react-material-ui-carousel/pull/2#pullrequestreview-2205186831" title="Approved">daniellalasa2</a>*, *<a href="https://github.com/ginbits/react-material-ui-carousel/pull/2#issuecomment-2256498389" title="Approved">gregpavl</a>*, *<a href="https://github.com/ginbits/react-material-ui-carousel/pull/2#" title="Author self-approved">shayan-ginbits</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ginbits%2Freact-material-ui-carousel).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ginbits/react-material-ui-carousel/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ginbits-bots** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by: *<a href="https://github.com/ginbits/react-material-ui-carousel/pull/2#pullrequestreview-2205186831" title="Approved">daniellalasa2</a>*, *<a href="https://github.com/ginbits/react-material-ui-carousel/pull/2#issuecomment-2256498389" title="Approved">gregpavl</a>*, *<a href="https://github.com/ginbits/react-material-ui-carousel/pull/2#" title="Author self-approved">shayan-ginbits</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=ginbits%2Freact-material-ui-carousel).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/ginbits/react-material-ui-carousel/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
